name: 'Setup project'
description: 'Sets up project and its dependencies'
env:
  APP_STAGE: dev
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v3
      with:
        version: ${{ env.PNPM_VERSION }}
        run_install: false

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        registry-url: https://npm.pkg.github.com
        cache: 'pnpm'
        cache-dependency-path: './pnpm-lock.yaml'

    # nextjs cache
    - uses: actions/cache@v4
      with:
        path: |
          ${{ github.workspace }}/.next/cache
        # Generate a new cache whenever packages or source files change.
        key:
          ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts',
          '**/*.tsx') }}
        # If source files changed but packages didn't, rebuild from a prior cache.
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

    - shell: bash
      run: |
        pnpm env use --global 20
        pnpm run env:init
        pnpm install -g turbo@latest bun@latest
        pnpm install --frozen-lockfile
